changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title:  🚀 新功能
      labels:
        - feat
        - feature
        - enhancement

    - title:  🐛 修复
      labels:
        - fix
        - bug
        - bugfix

    - title:  📚 文档
      labels:
        - docs
        - documentation

    - title:  ⚡ 性能
      labels:
        - perf
        - performance

    - title:  🔧 维护
      labels:
        - chore
        - refactor
        - ci
        - test
        - build
        - deps
        - dependencies

    - title:  其他变更
      labels:
        - "*"
